edxcs50_djangoapp/edxcs50_djangoapp/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('hello/', include('myapp.urls')),
    path('newyear/', include('newyear.urls')),
    path('tasks/', include('tasks.urls')),
    path('flights/', include('flights.urls')),
    path('users/', include('users.urls')),
]

edxcs50_djangoapp/flights/urls.py
from django.urls import path
from . import views
app_name = 'flights'
urlpatterns = [
    path('', views.index, name='index'),
    path('<int:flight_id>', views.flight, name='flight'),
    path('<int:flight_id>/book', views.book, name='book')
]

edxcs50_djangoapp/myapp/urls.py
from django.urls import path
from . import views
app_name = 'myapp'
urlpatterns = [
    path('', views.index, name='index'),
    # path('<str:name>', views.greet, name='greet'):
    path('singlepage', views.singlepage, name='singlepage'),
    path('singlepage/sections/<int:num>', views.section, name='section'),
    path('posts/all', views.posts_view, name='posts_view'),
    path('posts/', views.posts, name='posts'),
]

edxcs50_djangoapp/newyear/urls.py
from django.urls import path
from . import views

app_name = 'newyear'
urlpatterns = [
    path('', views.index, name='index')
]

edxcs50_djangoapp/tasks/urls.py
from django.urls import path
from . import views
app_name = 'tasks'
urlpatterns = [
    path('',views.index, name='index'),
    path('add', views.add, name='add')
]

edxcs50_djangoapp/users/urls.py
from django.urls import path
from . import views
app_name = 'users'
urlpatterns = [
    path('', views.index, name='index'),
    path('login', views.login_view, name='login'),
    path('logout', views.logout_view, name='logout'),
]

edxcs50_djangoapp/flights/models.py
from django.db import models

# Create your models here.
class Airport(models.Model):
    code = models.CharField(max_length=3)
    city = models.CharField(max_length=64)

    def __str__(self):
        return f'{self.city} ({self.code})'

class Flight(models.Model):
    origin = models.ForeignKey(Airport, on_delete=models.CASCADE, related_name='departures')
    destination = models.ForeignKey(Airport, on_delete=models.CASCADE, related_name='arrivals')
    duration  = models.IntegerField()

    def __str__(self):
        return f"{self.id}: {self.origin} to {self.destination}"
    def is_valid_flight(self):
        return self.origin != self.destination or self.duration > 0
    

class Passenger(models.Model):
    first = models.CharField(max_length=64)
    last = models.CharField(max_length=64)
    # blank = True to indicate passenger can have no flight
    flights = models.ManyToManyField(Flight, blank=True, related_name='passengers')

    def __str__(self):
        return f'{self.first} {self.last}'

edxcs50_djangoapp/users/models.py
from django.db import models

# Create your models here.

edxcs50_djangoapp/flights/views.py
from django.shortcuts import render
from .models import *
from django.http import HttpResponseRedirect
from django.urls import reverse

# Create your views here.
def index(request):
    return render(request, 'flights/index.html',{
        'flights':Flight.objects.all()
    })

def flight(request, flight_id):
    flight = Flight.objects.get(id=flight_id)
    passengers = Passenger.objects.all()
    non_passengers = Passenger.objects.exclude(flights=flight).all()
    return render(request,'flights/flight.html',{
        'flight':flight,
        'passengers':passengers,
        'non_passengers': non_passengers
    })

def book(request,flight_id):
    # For a post request, and a new flight
    if request.method == 'POST':
        # Accessing the flight
        flight = Flight.objects.get(pk=flight_id)

        # Finding the passenger id from the sumitted form data
        passenger_id = int(request.POST['passenger'])

        # Find the passenger based on the id
        passenger = Passenger.objects.get(pk=passenger_id)

        # Add the passenger to the flight
        passenger.flights.add(flight)

        # Redirect user to flight page
        return HttpResponseRedirect(reverse('flights:flight', args=(flight.id,)))

edxcs50_djangoapp/myapp/views.py
from django.shortcuts import render       
from django.http import Http404, HttpResponse, JsonResponse
import time

# Create your views here.

def index(request):
    return render(request, 'home/index.html')
def greet(request, name):
    return render(request, 'home/greet.html', {
        'name': name.capitalize()
    })

def singlepage(request):
    return render(request, 'singlepage/index.html')

texts = [ 
    'Text 1 lorem ipsomjsddjsdsjdhjdjsdjsdskjdsjdjsdjsdsjdskjd ssdjslkdjsaodids sdkshdkjshdsajdsad skdusdsahd sdksadhaksdsd sdsuhdsdjoiaddjpoisdpsa sidhsad', 
    'Text 2 sth ewiajd uasodosdodsdnsjdssdh sdaabaawiwdajwowpapjad didioeiurb ju nythsaodalaufewij uwaiuiefnaaioL uufeyuejhifkweorijn uiueiuffe iuifeuowq;foijaoffhufn hguaygif', 
    'Text 3 uo ooduhf trhetjj dudospweijffueu duwiiwkfdjnnookdihf yrieodnhussaodfjfnfuffnf idjdodihnkkdndhdhdijusjsodsj usjsoseydhjkwlewfjdkfkdfkjsijslkjdldourdifjdkudfdfjdnf',
    ]
def section(request, num):
    if 1 <= num <= 3:
       return HttpResponse(texts[num - 1])
    else:
        raise Http404('No such section')
    

def posts_view(request):
    return render(request, 'posts/index.html')

def posts(request):

    # Get start and end points
    start = int(request.GET.get('start') or 0)
    end = int(request.GET.get('end') or (start + 9))

    # Generate list of posts
    data = []
    for i in range(start, end+1):
        data.append(f'Post #{i}')

    # Artificially delay speed of response
    time.sleep(1) 

    # Return list of posts
    return JsonResponse({
        'posts': data
    })

edxcs50_djangoapp/newyear/views.py
from django.shortcuts import render
import datetime
# Create your views here.
def index(request):
    now = datetime.datetime.now()
    return render(request,'newyear/index.html', {
        'newyear': now.month == 1 and now.day == 1
    })

edxcs50_djangoapp/tasks/views.py
from django.shortcuts import render
from django import forms
from django.urls import  reverse
from django.http import HttpResponseRedirect


#List all tasks
def index(request): 
    # check if there already exists a 'tasks' key in our session
    if 'tasks' not in request.session:
       # if not, create a new list
       request.session['tasks'] = []

    return render(request, 'tasks/index.html',{
        'tasks':request.session['tasks']
    })

#Add new task:
def add(request):

 # check if method is POST
 if request.method == 'POST':
    # take in the data the user submit and save it as form
    form = NewTaskForm(request.POST)
    
    # check if form data is valid (server-side)
    if form.is_valid():
       
       # Isolate the task from the 'cleaned' version of form data
       task = form.cleaned_data['task']

       # Add the new task to our list tasks
       request.session['tasks'] += [task]

       # Redirect user to list of tasks
       return HttpResponseRedirect(reverse('tasks:index'))
    else:
       # if the form is invalid re-render the page with existing informatiion.
       return render(request,'tasks/add.html',{
          'form':form
       })


 return render(request, 'tasks/add.html',{
        'form':NewTaskForm()
    })

class NewTaskForm(forms.Form):
    task = forms.CharField(label='New Task')

edxcs50_djangoapp/users/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.urls import reverse
from django .contrib.auth import authenticate, login, logout
# Create your views here.
def index(request):
    # if no user is signed in, return to login page
    if not request.user.is_authenticated:
        return HttpResponseRedirect(reverse('users:login'))
    return render(request, 'users/user.html')

def login_view(request):
    if request.method == 'POST':
        # Accessing username and password from form data
        username = request.POST['username']
        password = request.POST['password']

        # Check if username and password are correct, returning User object if so
        user = authenticate(request, username=username, password=password)

        # If user object is returned, log in and route to index page:
        if user:
            login(request, user)
            return HttpResponseRedirect(reverse('users:index'))
        # Otherwise, return login page again with new context
        else:
            return render(request, 'users/login.html',{
                'message':'Invalid Credentials'
            })

    return render(request, 'users/login.html')

def logout_view(request):
    logout(request)
    return render(request,'users/login.html',{
        'message':'Logged Out'
    })
    

edxcs50_djangoapp/flights/templates/flights/flight.html
{% extends 'flights/layout.html' %}

{% block body %}
<h1>Flight {{flight.id}}</h1>
<ul>
    <li>Origin: {{flight.origin}} </li>
    <li>Destination: {{flight.destination}}</li>
    <li>Duration: {{flight.duration}} minutes</li>
</ul>
<div>
    <h2>Passengers:</h2>
    <ul>
        {% for passenger in passengers %}
        <li> {{passenger}} </li>
        {% empty %}
        <li>No Passengers.</li>
        {% endfor %}
    </ul>
</div>

<div>
    <h2>Add Passenger</h2>
    <form action="{% url 'flights:book' flight.id %}" method="post">
        {% csrf_token %}
        <select name="passenger">
            {% for passenger in non_passengers %}
            <option value="{{passenger.id}}">{{passenger}}</option>
            {% endfor %}
        </select>
        <input type="submit">
    </form>
</div>
<a href="{% url 'flights:index' %}">All flights</a>
{% endblock%}

edxcs50_djangoapp/flights/templates/flights/index.html
{% extends 'flights/layout.html' %}

{% block body %}
<h1>Flights :</h1>
<ul>
    {% for flight in flights %}
    <li><a href="{% url 'flights:flight' flight.id %}"> Flight {{ flight.id }}: {{ flight.origin }} to {{ flight.destination}}</a></li>
    {% endfor %}
</ul>
{% endblock %}

edxcs50_djangoapp/flights/templates/flights/layout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Flights</title>
</head>
<body>
    {% block body %}
    {% endblock %}
</body>
</html>

edxcs50_djangoapp/myapp/templates/home/greet.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Hello</title>
</head>
<body>
    <h1>Hello, {{ name }}</h1>
</body>
</html>

edxcs50_djangoapp/myapp/templates/home/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>home</title>
</head>
<body>
    <h1>Hello from home</h1>
</body>
</html>

edxcs50_djangoapp/myapp/templates/posts/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>My Webpage</title>
    <style>
        @keyframes hide {
            0% {
                opacity: 1;
                height: 100%;
                line-height: 100%;
                padding: 20px;
                margin-bottom: 10px;
            }

            75% {
                opacity: 0;
                height: 100%;
                line-height: 100%;
                padding: 20px;
                margin-bottom: 10px;
            }

            100% {
                opacity: 0;
                height: 0px;
                line-height: 0;
                padding: 0;
                margin-bottom: 0px;
            }
        }

        .post {
            background-color: #77dd11;
            padding: 20px;
            margin-bottom: 10px;
            animation-name: hide;
            animation-duration: 2s;
            animation-fill-mode:forwards;
            animation-play-state: paused;
        }

        body {
            padding-bottom: 50px;
        }
    </style>
    <script src="{% static 'posts/script.js' %}"></script>
</head>

<body>
    <div id="posts">
        <!-- display all posts here -->
    </div>
</body>

</html>

edxcs50_djangoapp/myapp/templates/singlepage/index.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Single page</title>
    <style>
        button {
            padding: 13px 5px;
            margin-left: 12px;
            margin-top: 15px;
            box-shadow: 1px 2px 5px rgb(17, 17, 16);
            border-color: bisque;
            background: white;
            border-radius: 5px;
            cursor: pointer;
        }

        #content {
            margin: 15px;
        }
    </style>
    <script>

        // When back arrow is clicked, show previous section
        window.onpopstate = function (event) {
            console.log(event.state.section);
            showsection(event.state.section);
        }

        // Shows given section
        function showsection(section) {

            // Find section text from server
            fetch(`singlepage/sections/${section}`)
                .then(response => response.text())
                .then(text => {
                    // Log text and display on page
                    console.log(text);
                    document.querySelector('#content').innerHTML = text;
                })
        }

        // Wait for the page to load
        document.addEventListener('DOMContentLoaded', () => {

            // Add button functionality
            document.querySelectorAll('button').forEach(button => {
                button.onclick = function () {
                    const section = this.dataset.section

                    // Add the current state to the history
                    history.pushState({section: section}, "", `section${section}`);
                    showsection(section);
                }
            })
        })
    </script>
</head>

<body>
    <h1>Hello!</h1>
    <button data-section="1">Section 1</button>
    <button data-section="2">Section 2</button>
    <button data-section="3">Section 3</button>
    <div id="content"></div>
</body>

</html>

edxcs50_djangoapp/newyear/templates/newyear/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Is it New Year's? </title>
    <link rel="stylesheet" href="{% static 'newyear/styles.css' %}">
</head>

<body>
    <div>
        {% if newyear %}
        <h1>Yes</h1>
        {% else %}
        <h1>No</h1>
        {% endif %}
    </div>
</body>

</html>

edxcs50_djangoapp/tasks/templates/tasks/add.html
{% extends 'tasks/layout.html' %}

{% block body %}
<h1>Add Task:</h1>
<form action="{% url 'tasks:add' %}" method="post">
    {% csrf_token %}
    {{form}}
    <input type="submit">
</form>
<a href="{% url 'tasks:index' %}">View Tasks</a>
{% endblock %}

edxcs50_djangoapp/tasks/templates/tasks/index.html
{% extends 'tasks/layout.html' %}

{% block body %}
    <ul>
        {% for task in tasks %}
        <li>{{task}} </li>
        {% endfor %}
    </ul>
    <a href="{% url 'tasks:add' %}">Add a New Task</a>
{% endblock %}

edxcs50_djangoapp/tasks/templates/tasks/layout.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Tasks</title>
</head>
<body>
    {% block body %}
    {% endblock %}
</body>
</html>

edxcs50_djangoapp/users/templates/users/layout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>USERS</title>
</head>
<body>
    {% block body %}
    
    {% endblock %}
</body>
</html>

edxcs50_djangoapp/users/templates/users/login.html
{% extends 'users/layout.html' %}

{% block body %}
{% if message %}
<div> {{message}} </div>
{% endif %}
  
<form action="{% url 'users:login' %}" method="post" >
    {% csrf_token %}
    <input type="text", name="username", placeholder="Username">
    <input type="password", name="password", placeholder="Password">
    <input type="submit", value="Login">
</form>
{% endblock %}

edxcs50_djangoapp/users/templates/users/user.html
{% extends 'users/layout.html' %}

{% block body %}
<h1>Welcome, {{request.user.first_name}}</h1>
<ul>
    <li>Username: {{request.user.username}} </li>
    <li>Email: {{request.user.email}} </li>
</ul>

<a href="{% url 'users:logout' %}">Log Out</a>
{% endblock %}